---
- name: restart zabbix-server
  systemd:
    name: zabbix-server
    state: restarted

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: install cpan modules
  shell:
    cmd: /usr/local/bin/cpanm --installdeps -L local .
    chdir: /usr/lib/zabbix/externalscripts
