---
- name: configure postfix
  debconf:
    name: postfix
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items:
    - { question: postfix/main_mailer_type, value: "Internet Site", vtype: select }
  changed_when: False

- name: install packages
  apt:
    name:
      - postfix
    update_cache: yes

- name: modify main.cf
  lineinfile:
    path: /etc/postfix/main.cf
    regexp: "^inet_interfaces"
    line: "inet_interfaces = loopback-only"
  notify: restart postfix
