---
- name: check os version
  fail: msg='OS is NOT Ubuntu 22.x'
  when: ansible_distribution != 'Ubuntu' or ansible_distribution_major_version != '22'

- name: update ca-certificates
  apt:
    name: ca-certificates
    state: latest
    update_cache: yes
